### ISSUE TITLE
what do the codes for iscandlelighting mean?

### ISSUE THREAD

**Issue by emaayan** [yparitcher/libzmanim#10]
it would have been nice to have an enum casue i'm not sure what does 1 2 and 3 mean in this case

i've started displaying the times part in the esp project 
any reason why i can't use 
setenv("TZ", "IST-2IDT,M3.4.4/26,M10.5.0", 1);
tzset();
to make the proper time zone match the one i'll putting on the timezone field? 

![image](https://user-images.githubusercontent.com/13434544/231794357-1ecef1c9-aa4d-4862-a4e7-aa100ffd20e8.png)

**Comment by yparitcher** [comment]
https://github.com/yparitcher/libzmanim/blob/63b350b4be6bb1b60c7fff91f343e11361ed823f/include/hebrewcalendar.h#L136-L137

You can set the timezone through the TZ env, for use by the C stdlib.

**Comment by emaayan** [comment]
> 

thanks, fortunely esp32 supports this api, so i've got 2 files files for cities and timezones from the net that contain major cities , their coordinates, and dst rules all in one shot . 
and trying generate c code out of it, so the user would only need to select nearest city next to them.
as you might have figured i've hit a "slight" problem in using nested arrays in a struct , but i guess i'll solve it somehow. 

```
struct zone
{
    const long id;
    const char name[11];
    const double lat;
    const double lng;
    const double elevation;
    const char timezone[32];
    const char dstRules[32];
};
struct country
{
    const char code[4];
    const char name[32];
    const zone zones[];
};

const country israel= {"ISR", "Israel", 
        {
         {0, "ehlhana", 232.22, 32.0, 3.0, "AsiaEurp", "sda32"}
        ,{1, "dsdlhana", 244.22, 344.0, 3.0, "AsiaEurpsd", "sda32232"}
        }};
const country us = {"US", "UnitedStates", 
        {
         {3, "tx", 232.22, 32.0, 3.0, "texas", "sda32"}
        ,{4, "ark", 244.22, 344.0, 3.0, "Arankso", "sda32"}
        }};

```
