### ISSUE TITLE
how compitble can this code be with esp32 ?

### ISSUE THREAD

**Issue by giggty** [yparitcher/libzmanim#14]
it has the capabilites and libraries i assume... or is it a dead end ? and better to drop it.... just asking ...

**Comment by yparitcher** [comment]
See https://github.com/yparitcher/libzmanim/issues/4#issuecomment-810455554 and following.

**Comment by emaayan** [comment]
> it has the capabilites and libraries i assume... or is it a dead end ? and better to drop it.... just asking ...



> it has the capabilites and libraries i assume... or is it a dead end ? and better to drop it.... just asking ...
I've been running it on my esp32 for  a rather long time i've been too lazy to enclose it. 

https://github.com/emaayan/HClock

ironically, the longest time was actually spent on integrating a menu system to allow you select a country and a city to provide geo location, i had to look around for a table of countries, cities and codes for day light saving times, and downsize it so it would inside the esp32. 
but i don't recall needing to change anything in particular for the library itself, i've been running with an arduino for a whole year, with just one small change to one function's signature. 

the intent was "re-create" a small hebrew desktop clock for the holidays we have and long longer being sold.
