### ISSUE TITLE
How to run the program on Windows

### ISSUE THREAD

**Issue by shmu26** [yparitcher/libzmanim#3]
I am a code-noob on Windows (I know linux a bit better)
I followed the instructions for installing on Windows: "run window.bat in a VisualStudio command prompt to build `libzmanim.dll` and `test.exe`. This uses the OpenBSD stpncpy."

I did it as follows:
"How do I run a .bat file in Visual Studio?

    Right click the batch file in the Solution Explorer.
    Select “Open With…” from the context menu.
    Click “Add…”
    In the “Program name” textbox, enter powershell.exe.
    In the “Friendly name” textbox enter “PowerShell”
    Select “Set As Default”
    Click OK."

Okay, so I ran it in powershell. What's the next step?
There were no error messages, but I don't see "test.exe" anywhere. 
How do I run the program?

**Comment by yparitcher** [comment]
You need to open a Visual Studio command prompt (not powershell) via the instructions here: https://docs.microsoft.com/en-us/cpp/build/building-on-the-command-line?view=msvc-160 then change directories to the libzmanim folder then run `.\windows.bat`

**Comment by shmu26** [comment]
And happy Purim!
