### ISSUE TITLE
Perkie Avos Erve Thisha BaV

### ISSUE THREAD

**Issue by elazarrosenthal** [yparitcher/libzmanim#5]
Its my understanding that we dont say Perkie Avos when 8 av is on Shabbos
your Avos code seems to  assign a perek to that day.
a version of 
Is this a chabad difference in minhagim ?

I just happened to notice because I was thinking of using your algorithem in an app I have for the java version of Kosher Java Zmanim
and that does not provied avos

Thanks

**Comment by zachweix** [comment]
I can't say I've heard of that Minhag. As far as I know, you just do a Perek a week, every week, until Rosh Hashana (and double up at the end if necessary)

**Comment by elazarrosenthal** [comment]
The code seems to cover when tisha bav itself is on shabbos 
but not erev tish bav 
ram 

as far as I know the minhag is the same for 8 av being on shabbos 

I did not go through the code comleately just put in this shabbos using test prog

**Comment by elazarrosenthal** [comment]
See:  mishna berura 553(2):9. ( (ט)תקנג ב )

https://www.mishnaberurayomi.org/pdf_pages/Chelek_6/1535_Siman_553_Seif_2b-Siman_554_Seif_1.pdf

and kitzur shulchan orech 125 - 4

https://www.chabad.org/library/article_cdo/aid/4297970/jewish/Chapter-125-Laws-of-Tishah-beAv-When-it-Occurs-on-Shabbos-or-on-Sunday.htm

although kitzur is not clear about shabbos 8 av

I checked with local chabad rabbi in washington heights 
he said chabad minhag is not to say 
but did not have source avail at his fingertips

**Comment by elazarrosenthal** [comment]
if I am right 
this fixes

        if (avos_day_of_week == 6) { // tisha bav is Shabbos
                if (avos_day == 104) {return 0;} // tisha bav
                if (avos_day > 104) {chapter -=1;} // after tisha bav
        } else if (avos_day_of_week == 5) { // tisha bav is Sunday
                if (avos_day == 103) {return 0;} // erev tisha bav
                if (avos_day > 103) {chapter -=1;} // after tisha bav
        } 

however my underdstanding f the code well enough to trust the chnage on my own

**Comment by elazarrosenthal** [comment]
Thanks for the quick fix
code also does not seem right for 
eretz yisroel when shabbos is 1st day of pesach
in 2022 8th day is Aril 23 
shoul dbe 1st perek in Eretz yistoel 

./test 2022 4  23  40.852011 -73.936119  -4.0 1


elazar@elazar-Lenovo-IdeaPad-130S-11IGM ~/zmanim/libzmanim/test $ ./test 2022 4  23  40.852011
 -73.936119  -4.0 1
              כ״ב ניסן תשפ״ב
              ותן ברכה
              פרשת אחרי מות
              ספירת העומר: ז
alos:               04:30 AM EDT
misheyakir:         05:11 AM EDT
sunrise:            06:04 AM EDT
shma:               09:27 AM EDT
tefila:             10:36 AM EDT
chatzos:            12:54 PM EDT
mincha gedola:      01:28 PM EDT
mincha ketana:      04:55 PM EDT
plag hamincha:      06:21 PM EDT
sunset:             07:43 PM EDT
shabbos ends:       08:27 PM EDT
פרשת אחרי מות
שביעי עם פירש״י
תהלים
ק״ו - ק״ז
תניא
וגם כי אין לו
־120־ כנ״ל פ״כ.
רמב״ם
הלכות סנהדרין
פרק רביעי
elazar@elazar-Lenovo-IdeaPad-130S-11IGM

**Comment by yparitcher** [comment]
> eretz yisroel when shabbos is 1st day of pesach
> in 2022 8th day is Aril 23
> shoul dbe 1st perek in Eretz yistoel

They do not say Avos that week as they have 7 weeks between Pesach and Shavous so the do like the rest of the world and start the next week in order to finish on Erev Shavous

**Comment by elazarrosenthal** [comment]
submitted above as new issue

**Comment by elazarrosenthal** [comment]
I think they do
HebDate android app when set for israel show perek 1 for that date

I believe I remember hearing they do
however

Im from here  and have never been there that shabbos so you are possibly
correct

**Comment by yparitcher** [comment]
https://www.hebrewbooks.org/pdfpager.aspx?req=30483&pgnum=257

**Comment by elazarrosenthal** [comment]
I was just about to back you up with this
ended in a chbad shul
https://shulchanaruchharav.com/halacha/pirkei-avos/

There are a lot of minhagim so leave the chabad way :)

I am from brooklyn I daveneed in a chabad shul there for a long time


Currently I am in washington height  and the KAJ minhag (not mine )

is to do it 3 times before shiva asar b tamuz (I would not ask for that)

If I need different Ill chance for myself

I also relized the reason fro the dupe was

1) I replied to email
2) I was not sure that worked so entered on website
 in this case just diff minhagim


Its not a bug

**Comment by elazarrosenthal** [comment]
more on the different minhagim

https://outorah.org/p/50778/
