### ISSUE TITLE
Perkie Avos in Israel 1st day pesach on Shabbos

### ISSUE THREAD

**Issue by elazarrosenthal** [yparitcher/libzmanim#6]
code also does not seem right for 
eretz yisroel when shabbos is 1st day of pesach
in 2022 8th day is Aril 23 
should dbe 1st perek in Eretz yistoel 

./test 2022 4  23  40.852011 -73.936119  -4.0 1

elazar@elazar-Lenovo-IdeaPad-130S-11IGM ~/zmanim/libzmanim/test $ ./test 2022 4  23  40.852011
 -73.936119  -4.0 1
              כ״ב ניסן תשפ״ב
              ותן ברכה
              פרשת אחרי מות
              ספירת העומר: ז
alos:               04:30 AM EDT
misheyakir:         05:11 AM EDT
sunrise:            06:04 AM EDT
shma:               09:27 AM EDT
tefila:             10:36 AM EDT
chatzos:            12:54 PM EDT
mincha gedola:      01:28 PM EDT
mincha ketana:      04:55 PM EDT
plag hamincha:      06:21 PM EDT
sunset:             07:43 PM EDT
shabbos ends:       08:27 PM EDT
פרשת אחרי מות
שביעי עם פירש״י
תהלים
ק״ו - ק״ז
תניא
וגם כי אין לו
־120־ כנ״ל פ״כ.
רמב״ם
הלכות סנהדרין
פרק רביעי
elazar@elazar-Lenovo-IdeaPad-130S-11IGM

**Comment by yparitcher** [comment]
https://github.com/yparitcher/libzmanim/issues/5#issuecomment-881120964

Please only ask once :)

**Comment by elazarrosenthal** [comment]
Sorry
I put in #5 and figured it was really a different  issue : )
