### ISSUE TITLE
do you have any major calculations on epoch time?

### ISSUE THREAD

**Issue by emaayan** [yparitcher/libzmanim#9]
the reason i'm asking is that i recently discovered that arduino c implemenation actually uses the year 2000 and not 1970 as the start date inorder to prolong what is known as the y2k38 https://en.wikipedia.org/wiki/Year_2038_problem

![image](https://user-images.githubusercontent.com/13434544/230852988-58cf4692-a890-4524-8f34-73de756869ef.png)

while esp32 c implemenation still uses 1970 as the start year.

**Comment by yparitcher** [comment]
No, only in the time_t named functions
